/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 bolt.gltf 
Author: Javier.Herrera (https://sketchfab.com/Javier.Herrera)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bolt-m10x25-hexagon-head-e35ca3a7f829449ba1e72259ed33a144
Title: Bolt M10x25 Hexagon Head
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
    const { nodes, materials } = useGLTF("/3D/bolt/bolt.gltf");
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={1.3}>
                <mesh
                    geometry={nodes.defaultMaterial.geometry}
                    material={materials.BoltSteel}
                    rotation={[Math.PI / 2, 0, 0]}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/3D/bolt/bolt.gltf");
